##  makeCacheMatrix is a function that creates a special matrix
##  object that can cache its inverse.
##
##  cacheSolve is a function that computes the inverse of the
##  matrix returned by makeCacheMatrix
##
##
##  This function will create a list that sets and retrieves cache information.
##

makeCacheMatrix <- function(x = matrix()) {
  mt <- NULL
  setreg <- function(z)
  {
    x  <<- z
    mt <<- NULL
  }
  getreg <- function()
  {
    x
  }
  set.inverse <- function (inverse)
  {
    mt <<- inverse
  }
  get.inverse <- function ()
  {
    mt
  }
  list(setreg = setreg,
       getreg = getreg,
       set.inverse = set.inverse,
       get.inverse = get.inverse)
}

##
##  The function cacheSolve will use as its argument the list generated by
##  makeCacheMatrix then proceeds to apply the following condition:
##  if the inverse is already been calculated, it will be retrieved from
##  the cache, if it is not, proceeds to compute it and returns it.
##

cacheSolve <- function(x, ...) {
  mt <- x$get.inverse()
  not <- is.null(mt)
  if(!not)
  {
    return(m)
  }
  mat <- x$getreg()
  mt <- solve(mat, ...)
  x$set.inverse(mt)
  mt
}